server:
  port: 8080

spring:
  mvc:
    format:
      date-time: iso
      date: iso
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    password: ${DB_PASSWORD:admin}
    username: ${DB_USERNAME:admin}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 50000
      pool-name: hikari-pool
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  liquibase:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
